### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by yetanothercarbot** [yetanothercarbot/pividbell#1]
- [ ] Hardware (PCB) design
  - [ ] Main PCB:
    - [x] Audio subsytem design
    - [x] Infrared LEDs
    - [x] Door release
    - [x] Screw terminals for power input
    - [x] RJ45 for interconnect
    - [ ] PCB prep (footprints, ERC)
    - [ ] PCB layout
  - [x] Capacitive Button PCB Design
- [ ] Case design
  - [x] Model existing recess box
  - [ ] Design front panel 
- [ ] Software
  - [ ] Basic MQTT doorbell functionality
  - [ ] RTSP/ONVIF/other video streaming functionality
  - [ ] Door release, door state functionality
  - [ ] Configuration UI (?)
- [ ] Documentation
  - [ ] General project information (mainly the README)
  - [ ] Assembly information
  - [ ] Software installation instructions
  - [ ] Software configuration options
